Task 1
RazerFord/formal-lang-course pull request #1
Opened 2023-02-23 20:22 UTC by RazerFord

2023-02-25 05:56 UTC, rustam-azimov requested changes

2023-02-25 05:56 UTC, rustam-azimov commented on tests/test_create_graph_two_cycles.py
Сам пулл реквест плохой, в нем не видна вся работа.
1) Нужно поменять имена функций, сделать более точными
2) Для get info использовать named tuple и g.edges(data=True) для меток

2023-02-26 16:10 UTC, RazerFord commented on tests/test_create_graph_two_cycles.py
1. Названия функций поменял
2. Использовал `named tuple`
Ссылка на PR https://github.com/RazerFord/formal-lang-course/pull/2 где можно увидеть, проделанную работу. Немного неаккуратно получилось, в следующий раз сделаю в одном PR.

2023-02-26 19:03 UTC, rustam-azimov approved these changes

2023-02-26 19:06 UTC, merged