Овчинников Егор. Задание 6
RazerFord/formal-lang-course pull request #9
Opened 2023-03-31 18:21 UTC by RazerFord

2023-04-01 11:10 UTC, rustam-azimov requested changes

2023-04-01 11:10 UTC, rustam-azimov commented on project/context_free_grammar.py
> +        cfg_gr.remove_useless_symbols()
Здесь можно убрать первое удаление бесполезных правил

2023-04-01 23:11 UTC, RazerFord commented on project/context_free_grammar.py
> +        cfg_gr.remove_useless_symbols()
Исправил

2023-04-02 08:54 UTC, rustam-azimov approved these changes

2023-04-06 20:09 UTC, merged